ATTRIBUTES = ["RED", "GREEN", "BLUE"]
NEIGHBORS = ["SELF", "NORTH", "NORTHEAST", "EAST", "SOUTHEAST", "SOUTH", "SOUTHWEST", "WEST"]

BASE_OPERATORS = ["/", "+", "*", "-", "%"]
COMPOUND_OPERATORS = BASE_OPERATORS.map{|s| s + "="}
OPERATORS = BASE_OPERATORS + COMPOUND_OPERATORS + ["="]
